<?php

/* Copyright (C) 2018 Julien Vaubourg <julien@vaubourg.com>
 * Contribute at https://github.com/jvaubourg/processwire-module-misc
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

class MiscVariationsPrices extends WireData implements Module {
  private $cart_tpl_name = 'cart';
  private $unit_pattern = '/\b([0-9]+[.,]?[0-9]*)\s*(mg|g|gr|kg|ml|l)\b/i';
  private $cart;

  public static function getModuleInfo() {
    return array(
      'title' => 'Misc - Get Variations Prices',
      'version' => 1,
      'summary' => 'Show price intervals, per kg, etc.',
      'icon' => 'angellist',
      'href' => 'https://github.com/jvaubourg/processwire-module-misc',
      'author' => 'Julien Vaubourg',
      'singular' => true,
      'autoload' => true,
      'requires' => 'PadLoper',
    );
  }

  public function init() {
    $this->cart = $this->modules->get('PadCart');
  }


  /***********************/
  /** PRIVATE FUNCTIONS **/
  /***********************/

  private function getMaxPriceVariation($p) {
    $max_variation = '';
    $max_price = -INF;

    foreach($p->children as $variation) {
      if($variation->product_price > $max_price) {
        $max_variation = $variation;
        $max_price = $variation->product_price;
      }
    }

    return $max_variation;
  }

  private function getMinPriceVariation($p) {
    $min_variation = '';
    $min_price = INF;

    foreach($p->children as $variation) {
      if($variation->product_price < $min_price) {
        $min_variation = $variation;
        $min_price = $variation->product_price;
      }
    }

    return $min_variation;
  }

  private function getPricePerKgIntervalText($p) {
    list($min_price, $min_weight, $min_unit, $min_unit_price) = $this->getPricePerKg($this->getMinPriceVariation($p));
    list($max_price, $max_weight, $max_unit, $max_unit_price) = $this->getPricePerKg($this->getMaxPriceVariation($p));

    if($min_weight == $max_weight) {
      $interval = "{$this->cart->renderPriceAndCurrency($min_price)} ($min_weight$min_unit";

      if($min_weight == 1) {
        $interval .= ')';
      } else {
        $interval .= ", {$this->cart->renderPriceAndCurrency($min_unit_price)}/$min_unit)";
      }
    } else {
      $interval = __("From") . " {$this->cart->renderPriceAndCurrency($min_price)} ($min_weight$min_unit, {$this->cart->renderPriceAndCurrency($min_unit_price)}/$min_unit)<br />";
      $interval .= __("to") . " {$this->cart->renderPriceAndCurrency($max_price)} ($max_weight$max_unit, {$this->cart->renderPriceAndCurrency($max_unit_price)}/$max_unit)";
    }

    return $interval;
  }

  private function getPriceIntervalText($p) {
    $min_price = $this->getMinPriceVariation($p)->product_price;
    $max_price = $this->getMaxPriceVariation($p)->product_price;

    if($min_price == $max_price) {
      $interval = $this->cart->renderPriceAndCurrency($min_price);

    } else {
      $interval = __("From") . " {$this->cart->renderPriceAndCurrency($min_price)} ";
      $interval .= __("to") . " {$this->cart->renderPriceAndCurrency($max_price)}";
    }

    return $interval;
  }


  /**********************/
  /** PUBLIC FUNCTIONS **/
  /**********************/

  public function hasPricePerKg($p) {
    if($p->children->count() > 0) {
      $first_variation = $p->children->get(0);
      $product_size = trim($first_variation->product_size);

      if(preg_match($this->unit_pattern, $product_size)) {
        return true;
      }
    }
    
    return false;
  }

  public function getPricePerKg($variation) {
    $product_price = (float) trim($variation->product_price);
    $product_size = trim($variation->product_size);

    preg_match($this->unit_pattern, $product_size, $matches);
    $weight = (float) str_replace(',', '.', $matches[1]);
    $unit = $matches[2];

    $unit_price = round($product_price / $weight, 2);

    return array(
      $product_price,
      $weight,
      $unit,
      $unit_price
    );
  }

  public function getVariationsPricesText($p) {
    if($this->hasPricePerKg($p)) {
      return $this->getPricePerKgIntervalText($p);

    } elseif($p->children->count() > 0) {
      return $this->getPriceIntervalText($p);

    } else {
      return $this->cart->renderPriceAndCurrency($p->product_price);
    }
  }
}
